{{- if and .Values.kubeSsh.hostKey.privateKey (not .Values.kubeSsh.hostKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-ssh.hostKeySecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kube-ssh.labels" . | nindent 4 }}
  {{- with .Values.kubeSsh.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.kubeSsh.hostKey.secretKey }}: |
{{ .Values.kubeSsh.hostKey.privateKey | indent 4 }}
{{- end }}
