apiVersion: ssh.xiaoshiai.cn/v1
kind: Access
metadata:
  name: notebook
  namespace: default
spec:
  selector:
    app: notebook
  credentials:
    - username: alice
      publicKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPJjO+3uspsX3jrw5xIZmdn3TJJQLrZ68kALV3/9hRXM kube-ssh-example
